services:
  frontend:
    container_name: observer-frontend-${CONFIG_NAME}
    image: ${DOCKERHUB_USERNAME}/observer-frontend:${TAG}
    ports:
      - "${PORT}:80"  
    restart: always
    networks:
      - observer_network


networks:
  observer_network:
    external: true
